[package]
name = "greptty"
version = "0.1.0"
authors = ["Realglobe Inc. <greptty@realglobe.jp>"]
edition = "2018"

[dependencies]
tokio = { version = "^0.2.22", features = ["full"] }
regex = "^1.3.9"
